version: '2.2'

services:
  orders:    
    build:
      context: .
      dockerfile: Orders/Dockerfile
  shippings:    
    build:
      context: .
      dockerfile: Shippings/Dockerfile
  client:    
    build:
      context: .
      dockerfile: Client/Dockerfile
