version: '2.2'

services:
  orders:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+;http://+
      - ASPNETCORE_HTTPS_PORT=5001
      # Export HTTPS dev certificate as pfx with your own password (directory should match volume below)
      #    dotnet dev-certs https -ep ${APPDATA}/ASP.NET/Https/aspnetapp.pfx -p mypassword
      - ASPNETCORE_Kestrel__Certificates__Default__Password=mypassword
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/root/.aspnet/https/aspnetapp.pfx
      - SHIPPINGS_URL=https://shippings:443
    ports:
      - "5000:80"
      - "5001:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  shippings:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+;http://+
      - ASPNETCORE_HTTPS_PORT=5003
      # Export HTTPS dev certificate as pfx with your own password (directory should match volume below)
      #    dotnet dev-certs https -ep ${APPDATA}/ASP.NET/Https/aspnetapp.pfx -p mypassword
      - ASPNETCORE_Kestrel__Certificates__Default__Password=mypassword
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/root/.aspnet/https/aspnetapp.pfx
    ports:
      - "5002:80"
      - "5003:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  products:
    environment:
      - SERVER_ADDRESS=0.0.0.0:5004
    ports:
      - "5004:5004"
  client:
    # Ctrl+p,q to exit terminal!
    environment:
      - ORDERS_URL=https://orders:443
      - SHIPPINGS_URL=https://shippings:443
      - PRODUCTS_NAME=products:5004
      - PRODUCTS_URL=https://products:443
